//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.7905
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Devgis.MapApp.Properties {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Devgis.MapApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _001 {
            get {
                object obj = ResourceManager.GetObject("001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _002 {
            get {
                object obj = ResourceManager.GetObject("002", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _003 {
            get {
                object obj = ResourceManager.GetObject("003", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _004 {
            get {
                object obj = ResourceManager.GetObject("004", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _005 {
            get {
                object obj = ResourceManager.GetObject("005", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _007 {
            get {
                object obj = ResourceManager.GetObject("007", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _008 {
            get {
                object obj = ResourceManager.GetObject("008", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _009 {
            get {
                object obj = ResourceManager.GetObject("009", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01 {
            get {
                object obj = ResourceManager.GetObject("01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _010 {
            get {
                object obj = ResourceManager.GetObject("010", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _011 {
            get {
                object obj = ResourceManager.GetObject("011", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _012 {
            get {
                object obj = ResourceManager.GetObject("012", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _013 {
            get {
                object obj = ResourceManager.GetObject("013", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _014 {
            get {
                object obj = ResourceManager.GetObject("014", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _015 {
            get {
                object obj = ResourceManager.GetObject("015", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _016 {
            get {
                object obj = ResourceManager.GetObject("016", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _017 {
            get {
                object obj = ResourceManager.GetObject("017", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _018 {
            get {
                object obj = ResourceManager.GetObject("018", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _019 {
            get {
                object obj = ResourceManager.GetObject("019", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _02 {
            get {
                object obj = ResourceManager.GetObject("02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _020 {
            get {
                object obj = ResourceManager.GetObject("020", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _021 {
            get {
                object obj = ResourceManager.GetObject("021", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _022 {
            get {
                object obj = ResourceManager.GetObject("022", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _023 {
            get {
                object obj = ResourceManager.GetObject("023", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _024 {
            get {
                object obj = ResourceManager.GetObject("024", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _025 {
            get {
                object obj = ResourceManager.GetObject("025", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _026 {
            get {
                object obj = ResourceManager.GetObject("026", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _027 {
            get {
                object obj = ResourceManager.GetObject("027", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _028 {
            get {
                object obj = ResourceManager.GetObject("028", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _029 {
            get {
                object obj = ResourceManager.GetObject("029", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _031 {
            get {
                object obj = ResourceManager.GetObject("031", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _032 {
            get {
                object obj = ResourceManager.GetObject("032", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _033 {
            get {
                object obj = ResourceManager.GetObject("033", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _034 {
            get {
                object obj = ResourceManager.GetObject("034", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _035 {
            get {
                object obj = ResourceManager.GetObject("035", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _036 {
            get {
                object obj = ResourceManager.GetObject("036", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _037 {
            get {
                object obj = ResourceManager.GetObject("037", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _038 {
            get {
                object obj = ResourceManager.GetObject("038", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _039 {
            get {
                object obj = ResourceManager.GetObject("039", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _040 {
            get {
                object obj = ResourceManager.GetObject("040", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _041 {
            get {
                object obj = ResourceManager.GetObject("041", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _042 {
            get {
                object obj = ResourceManager.GetObject("042", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _043 {
            get {
                object obj = ResourceManager.GetObject("043", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _044 {
            get {
                object obj = ResourceManager.GetObject("044", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _045 {
            get {
                object obj = ResourceManager.GetObject("045", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _046 {
            get {
                object obj = ResourceManager.GetObject("046", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _047 {
            get {
                object obj = ResourceManager.GetObject("047", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _048 {
            get {
                object obj = ResourceManager.GetObject("048", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _049 {
            get {
                object obj = ResourceManager.GetObject("049", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _050 {
            get {
                object obj = ResourceManager.GetObject("050", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g {
            get {
                object obj = ResourceManager.GetObject("g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap getst {
            get {
                object obj = ResourceManager.GetObject("getst", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Identify {
            get {
                object obj = ResourceManager.GetObject("Identify", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MapControl {
            get {
                object obj = ResourceManager.GetObject("MapControl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PANTOOL {
            get {
                object obj = ResourceManager.GetObject("PANTOOL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap printtool {
            get {
                object obj = ResourceManager.GetObject("printtool", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap shuanxin {
            get {
                object obj = ResourceManager.GetObject("shuanxin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbar {
            get {
                object obj = ResourceManager.GetObject("toolbar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 上对齐 {
            get {
                object obj = ResourceManager.GetObject("上对齐", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 上条记录 {
            get {
                object obj = ResourceManager.GetObject("上条记录", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 上移一层 {
            get {
                object obj = ResourceManager.GetObject("上移一层", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 上移到顶层 {
            get {
                object obj = ResourceManager.GetObject("上移到顶层", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 下对齐 {
            get {
                object obj = ResourceManager.GetObject("下对齐", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 下条记录 {
            get {
                object obj = ResourceManager.GetObject("下条记录", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 下沉到底层 {
            get {
                object obj = ResourceManager.GetObject("下沉到底层", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 下移一层 {
            get {
                object obj = ResourceManager.GetObject("下移一层", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 两点通视 {
            get {
                object obj = ResourceManager.GetObject("两点通视", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 交集取反 {
            get {
                object obj = ResourceManager.GetObject("交集取反", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 保存 {
            get {
                object obj = ResourceManager.GetObject("保存", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 保存工作空间 {
            get {
                object obj = ResourceManager.GetObject("保存工作空间", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 修剪到线段 {
            get {
                object obj = ResourceManager.GetObject("修剪到线段", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 倒圆角 {
            get {
                object obj = ResourceManager.GetObject("倒圆角", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 倒直角 {
            get {
                object obj = ResourceManager.GetObject("倒直角", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 偏移 {
            get {
                object obj = ResourceManager.GetObject("偏移", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 停止 {
            get {
                object obj = ResourceManager.GetObject("停止", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 全屏显示 {
            get {
                object obj = ResourceManager.GetObject("全屏显示", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 全幅显示 {
            get {
                object obj = ResourceManager.GetObject("全幅显示", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 关于 {
            get {
                object obj = ResourceManager.GetObject("关于", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 分解对象 {
            get {
                object obj = ResourceManager.GetObject("分解对象", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 列表 {
            get {
                object obj = ResourceManager.GetObject("列表", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 列设置 {
            get {
                object obj = ResourceManager.GetObject("列设置", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 刷新 {
            get {
                object obj = ResourceManager.GetObject("刷新", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 刺点 {
            get {
                object obj = ResourceManager.GetObject("刺点", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 前一视图 {
            get {
                object obj = ResourceManager.GetObject("前一视图", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 前进 {
            get {
                object obj = ResourceManager.GetObject("前进", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 剖面图 {
            get {
                object obj = ResourceManager.GetObject("剖面图", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 剪切 {
            get {
                object obj = ResourceManager.GetObject("剪切", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 升序 {
            get {
                object obj = ResourceManager.GetObject("升序", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 可视范围 {
            get {
                object obj = ResourceManager.GetObject("可视范围", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 右对齐 {
            get {
                object obj = ResourceManager.GetObject("右对齐", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 合并 {
            get {
                object obj = ResourceManager.GetObject("合并", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 后一视图 {
            get {
                object obj = ResourceManager.GetObject("后一视图", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 后退 {
            get {
                object obj = ResourceManager.GetObject("后退", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 向上一级 {
            get {
                object obj = ResourceManager.GetObject("向上一级", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 回放 {
            get {
                object obj = ResourceManager.GetObject("回放", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 回放飞行路径 {
            get {
                object obj = ResourceManager.GetObject("回放飞行路径", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 固定角度 {
            get {
                object obj = ResourceManager.GetObject("固定角度", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 固定长度 {
            get {
                object obj = ResourceManager.GetObject("固定长度", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 图层管理 {
            get {
                object obj = ResourceManager.GetObject("图层管理", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 圆形选择 {
            get {
                object obj = ResourceManager.GetObject("圆形选择", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 在中点 {
            get {
                object obj = ResourceManager.GetObject("在中点", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 在延长线上 {
            get {
                object obj = ResourceManager.GetObject("在延长线上", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 在现上 {
            get {
                object obj = ResourceManager.GetObject("在现上", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 垂直居中 {
            get {
                object obj = ResourceManager.GetObject("垂直居中", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 垂直水平等距 {
            get {
                object obj = ResourceManager.GetObject("垂直水平等距", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 垂直等距 {
            get {
                object obj = ResourceManager.GetObject("垂直等距", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 填充前景色 {
            get {
                object obj = ResourceManager.GetObject("填充前景色", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 填充背景色 {
            get {
                object obj = ResourceManager.GetObject("填充背景色", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 增加节点 {
            get {
                object obj = ResourceManager.GetObject("增加节点", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 复制 {
            get {
                object obj = ResourceManager.GetObject("复制", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 多边形选择 {
            get {
                object obj = ResourceManager.GetObject("多边形选择", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 大图标 {
            get {
                object obj = ResourceManager.GetObject("大图标", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 定位复制 {
            get {
                object obj = ResourceManager.GetObject("定位复制", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 小图标 {
            get {
                object obj = ResourceManager.GetObject("小图标", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 尾记录 {
            get {
                object obj = ResourceManager.GetObject("尾记录", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 局部放大 {
            get {
                object obj = ResourceManager.GetObject("局部放大", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 局部缩小 {
            get {
                object obj = ResourceManager.GetObject("局部缩小", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 属性刷 {
            get {
                object obj = ResourceManager.GetObject("属性刷", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 工作空间 {
            get {
                object obj = ResourceManager.GetObject("工作空间", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 左对齐 {
            get {
                object obj = ResourceManager.GetObject("左对齐", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 帮助 {
            get {
                object obj = ResourceManager.GetObject("帮助", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 平移 {
            get {
                object obj = ResourceManager.GetObject("平移", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 延伸到线段 {
            get {
                object obj = ResourceManager.GetObject("延伸到线段", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 录制 {
            get {
                object obj = ResourceManager.GetObject("录制", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 恢复 {
            get {
                object obj = ResourceManager.GetObject("恢复", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 打印 {
            get {
                object obj = ResourceManager.GetObject("打印", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 打开 {
            get {
                object obj = ResourceManager.GetObject("打开", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 打断 {
            get {
                object obj = ResourceManager.GetObject("打断", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 拆分 {
            get {
                object obj = ResourceManager.GetObject("拆分", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 按宽度显示 {
            get {
                object obj = ResourceManager.GetObject("按宽度显示", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 按长度显示 {
            get {
                object obj = ResourceManager.GetObject("按长度显示", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 捕捉设置 {
            get {
                object obj = ResourceManager.GetObject("捕捉设置", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 提取等值线 {
            get {
                object obj = ResourceManager.GetObject("提取等值线", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 撤消 {
            get {
                object obj = ResourceManager.GetObject("撤消", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 改变线方向 {
            get {
                object obj = ResourceManager.GetObject("改变线方向", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 放大 {
            get {
                object obj = ResourceManager.GetObject("放大", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 放大地图 {
            get {
                object obj = ResourceManager.GetObject("放大地图", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 放大布局 {
            get {
                object obj = ResourceManager.GetObject("放大布局", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 新建 {
            get {
                object obj = ResourceManager.GetObject("新建", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 旋转 {
            get {
                object obj = ResourceManager.GetObject("旋转", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 显示网格 {
            get {
                object obj = ResourceManager.GetObject("显示网格", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 显隐工作空间管理器 {
            get {
                object obj = ResourceManager.GetObject("显隐工作空间管理器", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 曲线光滑 {
            get {
                object obj = ResourceManager.GetObject("曲线光滑", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 最高点 {
            get {
                object obj = ResourceManager.GetObject("最高点", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 构建带孔多边形 {
            get {
                object obj = ResourceManager.GetObject("构建带孔多边形", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 查看对象属性 {
            get {
                object obj = ResourceManager.GetObject("查看对象属性", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 查询记录 {
            get {
                object obj = ResourceManager.GetObject("查询记录", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 查询高程 {
            get {
                object obj = ResourceManager.GetObject("查询高程", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 檫除 {
            get {
                object obj = ResourceManager.GetObject("檫除", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 檫除外部 {
            get {
                object obj = ResourceManager.GetObject("檫除外部", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 水平居中 {
            get {
                object obj = ResourceManager.GetObject("水平居中", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 水平等距 {
            get {
                object obj = ResourceManager.GetObject("水平等距", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 求交 {
            get {
                object obj = ResourceManager.GetObject("求交", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 沿线标注 {
            get {
                object obj = ResourceManager.GetObject("沿线标注", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 淹没模拟 {
            get {
                object obj = ResourceManager.GetObject("淹没模拟", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 漫游 {
            get {
                object obj = ResourceManager.GetObject("漫游", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 漫游1 {
            get {
                object obj = ResourceManager.GetObject("漫游1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 漫游2 {
            get {
                object obj = ResourceManager.GetObject("漫游2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 漫游地图 {
            get {
                object obj = ResourceManager.GetObject("漫游地图", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 漫游布局 {
            get {
                object obj = ResourceManager.GetObject("漫游布局", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 炸碎 {
            get {
                object obj = ResourceManager.GetObject("炸碎", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 点重合 {
            get {
                object obj = ResourceManager.GetObject("点重合", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 环游 {
            get {
                object obj = ResourceManager.GetObject("环游", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 画面分割 {
            get {
                object obj = ResourceManager.GetObject("画面分割", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 相交 {
            get {
                object obj = ResourceManager.GetObject("相交", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 移动对象 {
            get {
                object obj = ResourceManager.GetObject("移动对象", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 等宽 {
            get {
                object obj = ResourceManager.GetObject("等宽", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 等高 {
            get {
                object obj = ResourceManager.GetObject("等高", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 粘贴 {
            get {
                object obj = ResourceManager.GetObject("粘贴", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 线垂直 {
            get {
                object obj = ResourceManager.GetObject("线垂直", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 线条或点状符号的颜色 {
            get {
                object obj = ResourceManager.GetObject("线条或点状符号的颜色", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 线水平 {
            get {
                object obj = ResourceManager.GetObject("线水平", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 组合 {
            get {
                object obj = ResourceManager.GetObject("组合", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 组合对象 {
            get {
                object obj = ResourceManager.GetObject("组合对象", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 绕X轴旋转 {
            get {
                object obj = ResourceManager.GetObject("绕X轴旋转", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 绕Y轴旋转 {
            get {
                object obj = ResourceManager.GetObject("绕Y轴旋转", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 绕Z轴旋转 {
            get {
                object obj = ResourceManager.GetObject("绕Z轴旋转", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 绘制三点圆 {
            get {
                object obj = ResourceManager.GetObject("绘制三点圆", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 绘制三点弧线 {
            get {
                object obj = ResourceManager.GetObject("绘制三点弧线", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 绘制两点圆 {
            get {
                object obj = ResourceManager.GetObject("绘制两点圆", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 绘制图例 {
            get {
                object obj = ResourceManager.GetObject("绘制图例", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 绘制图片 {
            get {
                object obj = ResourceManager.GetObject("绘制图片", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 绘制圆心半径圆 {
            get {
                object obj = ResourceManager.GetObject("绘制圆心半径圆", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 绘制圆角 {
            get {
                object obj = ResourceManager.GetObject("绘制圆角", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 绘制圆角矩形 {
            get {
                object obj = ResourceManager.GetObject("绘制圆角矩形", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 绘制地图 {
            get {
                object obj = ResourceManager.GetObject("绘制地图", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 绘制多线段 {
            get {
                object obj = ResourceManager.GetObject("绘制多线段", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 绘制多边形 {
            get {
                object obj = ResourceManager.GetObject("绘制多边形", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 绘制平行四边形 {
            get {
                object obj = ResourceManager.GetObject("绘制平行四边形", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 绘制平行线 {
            get {
                object obj = ResourceManager.GetObject("绘制平行线", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 绘制弧 {
            get {
                object obj = ResourceManager.GetObject("绘制弧", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 绘制弧段 {
            get {
                object obj = ResourceManager.GetObject("绘制弧段", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 绘制折线 {
            get {
                object obj = ResourceManager.GetObject("绘制折线", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 绘制文字 {
            get {
                object obj = ResourceManager.GetObject("绘制文字", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 绘制文本 {
            get {
                object obj = ResourceManager.GetObject("绘制文本", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 绘制斜椭圆 {
            get {
                object obj = ResourceManager.GetObject("绘制斜椭圆", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 绘制方向标 {
            get {
                object obj = ResourceManager.GetObject("绘制方向标", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 绘制曲线 {
            get {
                object obj = ResourceManager.GetObject("绘制曲线", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 绘制椭圆 {
            get {
                object obj = ResourceManager.GetObject("绘制椭圆", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 绘制比例尺 {
            get {
                object obj = ResourceManager.GetObject("绘制比例尺", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 绘制点 {
            get {
                object obj = ResourceManager.GetObject("绘制点", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 绘制直线 {
            get {
                object obj = ResourceManager.GetObject("绘制直线", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 绘制矩形 {
            get {
                object obj = ResourceManager.GetObject("绘制矩形", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 绘制线 {
            get {
                object obj = ResourceManager.GetObject("绘制线", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 绘制自由曲线 {
            get {
                object obj = ResourceManager.GetObject("绘制自由曲线", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 绘制艺术字 {
            get {
                object obj = ResourceManager.GetObject("绘制艺术字", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 绘制表格 {
            get {
                object obj = ResourceManager.GetObject("绘制表格", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 绝对大小 {
            get {
                object obj = ResourceManager.GetObject("绝对大小", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 绝对居中 {
            get {
                object obj = ResourceManager.GetObject("绝对居中", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 统计 {
            get {
                object obj = ResourceManager.GetObject("统计", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 编辑节点 {
            get {
                object obj = ResourceManager.GetObject("编辑节点", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 缩小 {
            get {
                object obj = ResourceManager.GetObject("缩小", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 缩小地图 {
            get {
                object obj = ResourceManager.GetObject("缩小地图", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 缩小布局 {
            get {
                object obj = ResourceManager.GetObject("缩小布局", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 网格捕捉 {
            get {
                object obj = ResourceManager.GetObject("网格捕捉", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 自动切割面 {
            get {
                object obj = ResourceManager.GetObject("自动切割面", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 自动打断线 {
            get {
                object obj = ResourceManager.GetObject("自动打断线", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 自动移屏 {
            get {
                object obj = ResourceManager.GetObject("自动移屏", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 自动跟踪现 {
            get {
                object obj = ResourceManager.GetObject("自动跟踪现", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 自动跟踪面 {
            get {
                object obj = ResourceManager.GetObject("自动跟踪面", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 自由缩放 {
            get {
                object obj = ResourceManager.GetObject("自由缩放", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 自由缩放1 {
            get {
                object obj = ResourceManager.GetObject("自由缩放1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 自由缩放2 {
            get {
                object obj = ResourceManager.GetObject("自由缩放2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 表面积计算 {
            get {
                object obj = ResourceManager.GetObject("表面积计算", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 计算误差 {
            get {
                object obj = ResourceManager.GetObject("计算误差", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 设置三维背景 {
            get {
                object obj = ResourceManager.GetObject("设置三维背景", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 设置文本风格 {
            get {
                object obj = ResourceManager.GetObject("设置文本风格", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 设置点风格 {
            get {
                object obj = ResourceManager.GetObject("设置点风格", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 设置线风格 {
            get {
                object obj = ResourceManager.GetObject("设置线风格", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 设置面风格 {
            get {
                object obj = ResourceManager.GetObject("设置面风格", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 设置飞行路径 {
            get {
                object obj = ResourceManager.GetObject("设置飞行路径", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 详细信息 {
            get {
                object obj = ResourceManager.GetObject("详细信息", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 跟踪回退 {
            get {
                object obj = ResourceManager.GetObject("跟踪回退", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 跟踪设置 {
            get {
                object obj = ResourceManager.GetObject("跟踪设置", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 跨图层编辑 {
            get {
                object obj = ResourceManager.GetObject("跨图层编辑", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 输出窗口 {
            get {
                object obj = ResourceManager.GetObject("输出窗口", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 连接线对象 {
            get {
                object obj = ResourceManager.GetObject("连接线对象", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 选择 {
            get {
                object obj = ResourceManager.GetObject("选择", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 选择物体 {
            get {
                object obj = ResourceManager.GetObject("选择物体", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 配准 {
            get {
                object obj = ResourceManager.GetObject("配准", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 重新执行 {
            get {
                object obj = ResourceManager.GetObject("重新执行", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 重采样 {
            get {
                object obj = ResourceManager.GetObject("重采样", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 量算角度 {
            get {
                object obj = ResourceManager.GetObject("量算角度", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 量算距离 {
            get {
                object obj = ResourceManager.GetObject("量算距离", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 量算面积 {
            get {
                object obj = ResourceManager.GetObject("量算面积", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 锁定地图 {
            get {
                object obj = ResourceManager.GetObject("锁定地图", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 镜像 {
            get {
                object obj = ResourceManager.GetObject("镜像", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 降序 {
            get {
                object obj = ResourceManager.GetObject("降序", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 风格刷 {
            get {
                object obj = ResourceManager.GetObject("风格刷", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 首记录 {
            get {
                object obj = ResourceManager.GetObject("首记录", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 鼠标查询高程 {
            get {
                object obj = ResourceManager.GetObject("鼠标查询高程", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
